language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
matrix:
    allow_failures:
        - php: nightly
branches:
  only:
    - master
	- modular-rewrite
before_script:
  - wget https://www.phing.info/get/phing-latest.phar
script:
  - php phing-latest.phar -f build.xml phplint
install:
  - composer self-update
  - composer install --prefer-source --no-interaction